### ISSUE TITLE
Uncaught ViesException using checkExistence=true

### ISSUE THREAD

**Issue by PaddyLock** [ddeboer/vatin#12]
If I use the validation with checkExistence=true

    @Vatin(checkExistence=true)

I am getting the following error:

Error communicating with VIES service
500 Internal Server Error - ViesException
1 linked Exception: SoapFault »

ViesException: Error communicating with VIES service
SoapFault: SERVER_BUSY

Can this Exception be caught?

Thanks

**Comment by ddeboer** [comment]
So you’re using the bundle, right? In that case, unfortunately, no. Perhaps we could add a flag `ignoreExceptions` in the validation annotation?

**Comment by PaddyLock** [comment]
Hi, yes I'm using the bundle. Yes that solution would be ideal as for my use case it is only a check on the number to help reduce mistakes.

**Comment by ddeboer** [comment]
Could you please open an issue for this on the [bundle](https://github.com/ddeboer/vatin-bundle)?
