### ISSUE TITLE
Speed of VIES

### ISSUE THREAD

**Issue by roelvanduijnhoven** [ddeboer/vatin#18]
The web service is not responding for me. I don't get results within 30 seconds. Is this simply a problem with VIES at the moment? Or is this service no longer available?

**Comment by sstok** [comment]
It seem to be down at the moment.
http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl

**Comment by ddeboer** [comment]
As we already handle this correctly (see the Travis log for the build that is currently failing because of this) there's nothing else that we can do for now. If the problem persists, we may have to look for an alternative service.

**Comment by GrahamCampbell** [comment]
Yeh, the validation service has been offline quite a lot recently. :(

**Comment by roelvanduijnhoven** [comment]
Mm. Too bad. So I guess I am *not* going to use that service. Are there any alternative services available that we could be thinking about implementing (as other adapters)?

**Comment by GrahamCampbell** [comment]
None that I'm aware of.
