### ISSUE TITLE
Proposal: Make Validator callable?

### ISSUE THREAD

**Issue by tomkyle** [ddeboer/vatin#25]
So validating single records is quite easy with `$bool = $validator->isValid('NL123456789B01')`. When using with FilterIterators, i.e. `CallbackFilterIterator`, I feel it would be useful to make the Validator class callable. 

My proposal is to alias the _isValid_ method with a new **__invoke** method. One could then do:

```php
$is_valid = new Validator;
$bool = $is_valid('NL123456789B01');
```
or, respectively:

```php
$my_records = ask_database();
$is_valid = new Validator;
$valid_records = new \CallbackFilterIterator( $my_records, $is_valid);
```

What do you think?

**Comment by andreasschroth** [comment]
Hm, shouldn't something like this do the job?

```
$my_records = ask_database();
$validator = new Validator;
$valid_records = new \CallbackFilterIterator( $my_records, function ($record) use ($validator) { return $validator->isValid($record); });
```

**Comment by ddeboer** [comment]
I’m closing this, as I think @andreasschroth is right.

Thanks for reporting, @tomkyle!
