### ISSUE TITLE
Non EU vat numbers ?

### ISSUE THREAD

**Issue by mikeSimonson** [ddeboer/vatin#3]
Hi,

According to [this wikipedia page](https://en.wikipedia.org/wiki/VAT_identification_number) there are other countries that use VAT numbers.
Would you consider a pull request to add the validation necessary for those other countries even if the VIES system is not usable for thoses (I suppose).

Thanks

**Comment by ddeboer** [comment]
Closing due to lack of feedback. Feel free to re-open or submit a PR if this is still relevant to you.
