### ISSUE TITLE
CH country

### ISSUE THREAD

**Issue by martinknor** [ddeboer/vatin#33]
Use CH country code here `https://github.com/ddeboer/vatin/blob/master/src/Validator.php#L27` when VIES doesn't work with it. https://ec.europa.eu/taxation_customs/vies/faq.html?locale=lt#item_11

**Comment by martinknor** [comment]
+ also NO

**Comment by luggesexe** [comment]
What exactly is the issue? The country code NO and CH are in use. The VIES Service throws an invalid error when requested.

**Comment by ddeboer** [comment]
Closing due to lack of feedback.
