### ISSUE TITLE
GB does not validate against the VIES

### ISSUE THREAD

**Issue by ostark** [ddeboer/vatin#36]
Because of BREXIT, the EU API (VIES) does not validate `GB` VATINs anymore.
There is an API provided by the HMRC https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-registered-companies-api/1.0#_get-a-vat-registration_get_accordion

Not sure if this is beyond the scope of this package.

**Comment by GrahamCampbell** [comment]
You need to register for an API key with HMRC to use that API.

**Comment by ostark** [comment]
@GrahamCampbell True. It uses OAuth. Luckily it does not require a redirect-OAuth-flow, this means you can request the OAuth token and use it right after.

**Comment by bytespider** [comment]
I've just checked the documentation:
> Authorisation
> This endpoint is open access and requires no Authorization header.

**Comment by GrahamCampbell** [comment]
They must have recently changed this. since it was auth-walled, before.

**Comment by ostark** [comment]
I did a quick test on the `https://api.service.hmrc.gov.uk/organisations/vat/check-vat-number/lookup/{id}` endpoint. True, it's publicly accessible now.

**Comment by GrahamCampbell** [comment]
Validation of UK VAT IDs is out of scope of this package, anyway. This package is here for EU VAT IDs. If we add UK VAT IDs, where do we stop? Australian GST?

**Comment by ostark** [comment]
@GrahamCampbell Australia? This comparison makes no sense. 
Maybe you remember the days when the GB was part of the EU? And there is a tiny tiny chance the mistake gets reverted in the future.

But it's okay - that's why I asked.
